spring:
  application:
    name: PAYMENTS  # Unique name for the service
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URI
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    fetch-registry: true
    register-with-eureka: true


#spring:
#  application:
#    name: "PAYMENTS"  # Name of the service in Eureka
#
#server:
#  port: 8084
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
#    fetch-registry: true
#    register-with-eureka: true


#spring.application.name=PAYMENTS
#spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce
#spring.data.mongodb.database=Ecommerce_Payments
#server.port=8084
#service registry
## Eureka Client Configuration
#spring.application.name=PAYMENTS
#  # Change this for each service
#server.port=8084
#  # Change the port for each service
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#  # Eureka Server URL
#eureka.instance.prefer-ip-address=true
#  # Optional: Use IP instead of hostname
