spring:
  application:
    name: CUSTOMERS  # Unique name of the service
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URI
  data:
    mongodb:
      uri: mongodb://localhost:27017/Ecommerce-CUSTOMERS
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    fetch-registry: true
    register-with-eureka: true


#spring:
#  application:
#    name: "CUSTOMERS"  # Name of the service in Eureka
#server:
#  port: 8082
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
#    fetch-registry: true
#    register-with-eureka: true





#spring.application.name=Customer
#server.port=8082
#spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce
#spring.data.mongodb.database=Ecommerce_Customer
#
## Eureka Client Configuration
#spring.application.name=Customer
## Change this for each service
#server.port=8082
## Change the port for each service
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
## Eureka Server URL
#eureka.instance.prefer-ip-address=true
## Optional: Use IP instead of hostname
