spring:
  application:
    name: ORDERS  # Unique name for the service
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URI
  data:
    mongodb:
      uri: mongodb://localhost:27017/Ecommerce-ORDERS
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    fetch-registry: true
    register-with-eureka: true



#spring:
#  application:
#    name: "ORDERS"  # Name of the service in Eureka
#
#server:
#  port: 8083
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
#    fetch-registry: true
#    register-with-eureka: true


#spring.application.name=ORDERS
#server.port=8083
#spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce
#spring.data.mongodb.database=Ecommerce_Orders

## Eureka Client Configuration
#spring.application.name=ORDERS
## Change this for each service
#server.port=8083
## Change the port for each service
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
## Eureka Server URL
#eureka.instance.prefer-ip-address=true
## Optional: Use IP instead of hostname
