spring:
  application:
    name: "APIGATEWAY"

  cloud:
    gateway:
      routes:
        - id: CUSTOMERS
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
        - id:  ORDERS
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
        - id: ORDERSTATUS
          uri: http://localhost:8085
          predicates:
            - Path=/orderstatus/**
        - id: PAYMENTS
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**
        - id: PRODUCTS
          uri: http://localhost:8081
          predicates:
            - Path=/products/**


  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.client: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.cloud.gateway.route: DEBUG
    org.springframework.cloud.gateway.support: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.web.servlet: DEBUG

#spring:
#  application:
#    name: "APIGATEWAY"
#
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMERS
#          predicates:
#            - Path=/customers/**
#
#        - id: order-service
#          uri: lb://ORDERS
#          predicates:
#            - Path=/orders/**
#
#        - id: orderstatus-service
#          uri: lb://ORDERSTATUS
#          predicates:
#            - Path=/orderstatus/**
#
#        - id: payment-service
#          uri: lb://PAYMENTS
#          predicates:
#            - Path=/payments/**
#
#        - id: product-service
#          uri: lb://PRODUCTS
#          predicates:
#            - Path=/products/**
#
#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
#      fetch-registry: true
#      register-with-eureka: true
#
#server:
#  port: 8080  # API Gateway port

#spring:
#  application:
#    name: "APIGATEWAY"
#
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMERS
#          predicates:
#            - Path=/customers/**
#
#        - id: order-service
#          uri: lb://ORDERS
#          predicates:
#            - Path=/orders/**
#
#        - id: orderstatus-service
#          uri: lb://ORDERSTATUS
#          predicates:
#            - Path=/orderstatus/**
#
#        - id: payment-service
#          uri: lb://PAYMENTS
#          predicates:
#            - Path=/payments/**
#
#        - id: product-service
#          uri: lb://PRODUCTS
#          predicates:
#            - Path=/products/**
#
#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/
#      fetch-registry: true
#      register-with-eureka: true
#
#server:
#  port: 8080


#spring:
#  application:
#    name: "APIGATEWAY"
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMER
#          predicates:
#            - Path=/customers/**
#
#        - id: order-service
#          uri: lb://ORDERS
#          predicates:
#            - Path=/orders/**
#
#        - id: orderstatus-service
#          uri: lb://ORDERSTATUS
#          predicates:
#            - Path=/orderstatus/**
#
#        - id: payment-service
#          uri: lb://PAYMENTS
#          predicates:
#            - Path=/payments/**
#
#        - id: product-service
#          uri: lb://PRODUCTS
#          predicates:
#            - Path=/products/**
#
## Eureka Configurations (only in API Gateway)
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Eureka server URL (use your own if different)
#
#
#



#spring.application.name=APIGATEWAY
## API Gateway Name
#
#
## Eureka Client Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
## API Gateway Port
#server.port=8080
