spring:
  application:
    name: "APIGATEWAY"

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER
          predicates:
            - Path=/customers/**

        - id: order-service
          uri: lb://ORDERS
          predicates:
            - Path=/orders/**

        - id: orderstatus-service
          uri: lb://ORDERSTATUS
          predicates:
            - Path=/orderstatus/**

        - id: payment-service
          uri: lb://PAYMENTS
          predicates:
            - Path=/payments/**

        - id: product-service
          uri: lb://PRODUCTS
          predicates:
            - Path=/products/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

server:
  port: 8080


#spring:
#  application:
#    name: "APIGATEWAY"
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: customer-service
#          uri: lb://CUSTOMER
#          predicates:
#            - Path=/customers/**
#
#        - id: order-service
#          uri: lb://ORDERS
#          predicates:
#            - Path=/orders/**
#
#        - id: orderstatus-service
#          uri: lb://ORDERSTATUS
#          predicates:
#            - Path=/orderstatus/**
#
#        - id: payment-service
#          uri: lb://PAYMENTS
#          predicates:
#            - Path=/payments/**
#
#        - id: product-service
#          uri: lb://PRODUCTS
#          predicates:
#            - Path=/products/**
#
## Eureka Configurations (only in API Gateway)
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Eureka server URL (use your own if different)
#
#
#



#spring.application.name=APIGATEWAY
## API Gateway Name
#
#
## Eureka Client Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
## API Gateway Port
#server.port=8080
