#spring.application.name=CONFIGSERVER
server:
  port: 8888
spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/ecommerce-config-repo
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#server:
#  port: 8888
#
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config/
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#
